name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Set up JDK 11
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
